import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'mr' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  "en": {
    "kisanCallCentre": "Kisan Call Centre:",
    "farmerFirst": "Farmer First",
    "tagline": "Strengthening Market Linkages & Price Discovery for Farmers",
    "priceDiscovery": "01 Price Discovery",
    "netRealisation": "02 Net Realisation",
    "fpoAggregation": "03 FPO Aggregation",
    "sellWait": "04 Sell Now / Wait",
    "buyerMatching": "05 Buyer Matching & Bidding",
    "cropRescue": "Crop Rescue",
    "verifiedMandi": "e-NAM Standard Compliant",
    "sihPrototype": "Smart India Hackathon 2024–26 Prototype",
    "helplineHours": "Kisan Helpline: 1800-180-1551 (Mon-Sat, 06:00 - 20:00 IST)",
    "directBuyerConnection": "DIRECT BUYER CONNECTION",
    "zeroIntermediaryDeductions": "Zero Intermediary Deductions",
    "buyerMatchingTitle": "05 Direct Buyer Matching",
    "buyerMatchingSubtitle": "Tell us what you have in the field or warehouse. We connect you directly with verified institutional buyers, food processors, and retail chains looking for your exact crop, grade, and volume.",
    "activeBuyers": "Active Buyers",
    "defaultActiveBuyers": "18 Active Buyers",
    "readyIn": "Ready in",
    "cluster": "Cluster",
    "escrowGuaranteed": "🔒 100% Escrow Guaranteed",
    "step1Listed": "1. Produce Listed",
    "step2Matched": "2. Matched Buyers",
    "step3Terms": "3. Suitable Terms",
    "step4Offer": "4. Active Offer",
    "step5Deal": "5. Digital Deal",
    "step6Dispatch": "6. Dispatch & DBT",
    "topLeads": "Top Leads",
    "gatePickups": "Gate Pickups",
    "lockEscrow": "Lock Escrow",
    "bankPayout": "24h Bank Payout",
    "matchingVerifiedBuyers": "Matching verified institutional buyers...",
    "noMatchingBuyersFound": "No matching buyers found for",
    "tryDifferentCrop": "Try a different crop or reduce the quantity.",
    "emergencyDispatchContingency": "Emergency Dispatch Contingency",
    "emergencyDispatchDesc": "Facing buyer cancellation, gate rejection, or transport delay for your",
    "openCropRescue": "Open Crop Rescue (Module 06) →",
    "enamCompliant": "🔒 e-NAM Standard Compliant • AgriStack Protocol Node #412",
    "fetchBuyersFailed": "Failed to fetch matching buyers. Please try again.",
    "offerSent": "✅ Offer sent to",
    "andSavedBid": "and saved (Bid #",
    "sendOfferFailed": "Failed to send offer. Please try again.",
    "counterOfferSent": "Counter-offer",
    "sentTo": "sent to",
    "counterOfferFailed": "Counter-offer failed. Please try again.",
    "dealConfirmed": "🎉 Deal confirmed with",
    "transactionCreated": "created.",
    "acceptOfferFailed": "Failed to accept offer. Please try again.",
    "offerDeclined": "Offer declined.",
    "offerFrom": "Offer from",
    "declined": "declined.",
    "declineConfirm1": "Decline",
    "declineConfirm2": "'s offer? This cannot be undone.",
    "downloadingContract": "📄 Downloading e-NAM Digital Contract PDF...",
    "gatePassGenerated": "🎟️ Dispatch Gate Pass generated. Report to FPO Hub.",
    "emergencyModeActive": "Emergency Mode Active",
    "clusterLabel": "Cluster:",
    "apmcYardLabel": "APMC Yard",
    "cropRescueDesc": "Something went wrong with your scheduled crop dispatch? Don't panic. KrishiVaani instantly mobilizes fallback buyers, cold bay holds, and nearby open mandi yards.",
    "avgFallbackResolution": "Avg. Fallback Resolution:",
    "fourteenMins": "14 Mins",
    "hideIncidentHistory": "Hide Incident History",
    "myIncidents": "My Incidents",
    "step1Identified": "1. Problem Identified",
    "buyer_cancelled_title": "Buyer Cancelled",
    "transport_problem_title": "Transport Problem",
    "quality_dispute_title": "Quality Dispute",
    "other_emergency_title": "Other Emergency",
    "step2RescueStrategy": "2. Rescue Strategy",
    "selectAltPath": "Select Alternative Path",
    "step3InstantMatches": "3. Instant Matches",
    "verifiedBuyers": "Verified Buyers",
    "step4TakeAction": "4. Take Action",
    "dispatchOrSecure": "Dispatch or Secure Hold",
    "registeredCasesTitle": "Registered Rescue Cases in PostgreSQL",
    "totalLoggedIncidents": "total logged incidents",
    "failedLoadCrops": "Failed to load crop catalog from server.",
    "failedFetchMandis": "Failed to fetch nearby mandi prices.",
    "moduleActiveSync": "MODULE 01 ACTIVE • SYNCED WITH AGMARKNET & e-NAM",
    "updatedMinsAgo": "| Updated 15 mins ago (Live Feed)",
    "priceDiscoveryTitle": "Price Discovery",
    "priceDiscoverySubtitle": "Check current crop spot prices across local APMC mandis before taking produce off-farm.",
    "originLocationCaps": "ORIGIN LOCATION",
    "changeLocationBtn": "Change 📍",
    "selectYourCropTitle": "Select Your Crop",
    "clickCommodityHint": "Click any commodity to update APMC yard prices",
    "loadingCropsMsg": "Loading crop commodities...",
    "moreCropsBtn": "+41 More",
    "allIndiaIndexTxt": "All India Index",
    "nearbySpotPricesTitle": "Nearby APMC Mandi Spot Prices",
    "mandiGradeTxt": "Mandi Grade: FAQ Hybrid",
    "fetchingVerifiedPricesWithin": "Fetching verified spot prices within",
    "kmSuffix": "km...",
    "noMandisFoundWithin": "No APMC mandis found within",
    "km": "km",
    "expandSearchRadiusHint": "Try expanding your search radius to 50 km or 100 km, or search for a specific market yard below.",
    "expandRadius100kmBtn": "Expand Radius to 100 km",
    "module3Active": "MODULE 03 ACTIVE • FPO PRODUCE AGGREGATION & CONTRACT FULFILLMENT",
    "fpoAggregationTitle": "03 FPO Aggregation",
    "fpoAggregationDesc": "Combine your {quantity} Q with neighbor farmers to fulfill institutional orders.",
    "enamFpoGateway": "e-NAM FPO GATEWAY v4.2",
    "baramatiKisanProducer": "Baramati Kisan Producer Co. (Reg: FPO-MH-2024-882)",
    "step01BuyerRequirement": "STEP 01: Buyer Requirement",
    "step02FilterFarmers": "STEP 02: Filter Farmers",
    "step03AggregateQuantity": "STEP 03: Aggregate Quantity",
    "step04GenerateFpoLot": "STEP 04: Generate FPO Lot",
    "step05ContractPayout": "STEP 05: Contract Payout",
    "loadingVerifiedBuyerReqs": "Loading verified buyer requirements...",
    "buyerPurchaseOfferAccepted": "🎉 Buyer Purchase Offer Accepted! e-NAM Escrow Contract #AGR-MH-2026-904 Activated.",
    "counterBidTransmitted": "Counter-bid (+₹1.00/kg) transmitted to institutional procurement desk.",
    "smartContractId": "Smart Contract #SC-MH-2026-904",
    "zeroCommissionCompliant": "Zero Commission Mandate Compliant",
    "fastTrackSettlement": "Fast-track Settlement Protocol",
    "lastSyncInfo": "Last Sync: Today, 11:42 AM IST • Baramati Aggregation Center",
    "loginTitle": "Know your market.",
    "loginSubtitle": "Understand your earnings.",
    "heroDesc": "Empowering Indian farmers through transparent price discovery.",
    "heroSubDesc": "Real-time APMC price discovery across Maharashtra, with transparent net realization after freight & deductions, and direct linkage with verified buyers.",
    "farmersBuyersTitle": "Farmers & Verified Buyers",
    "farmersBuyersDesc": "Transparent price discovery with verified institutional buyers.",
    "maharashtraMandisTitle": "Maharashtra State Mandis",
    "maharashtraMandisDesc": "Live APMC mandi rates and market information.",
    "termsConditions": "Terms & Conditions",
    "privacyPolicy": "Privacy Policy",
    "aboutUs": "About Us",
    "allRightsReserved": "© 2025 KrishiVaani. All Rights Reserved.",
    "securePortalAccess": "Secure Portal Access",
    "welcomeTitle": "Welcome to KrishiVaani",
    "welcomeSubtitle": "Sign in to access price discovery, buyer linkages & mandi insights",
    "errorEmptyId": "Please enter your mobile number or email address",
    "errorEmptyPassword": "Please enter your password",
    "errorLoginFailed": "Login failed. Please check credentials.",
    "errorServer": "Unable to connect to server. Please try again.",
    "mobileOrEmailLabel": "Mobile Number or Email",
    "mobileOrEmailPlaceholder": "e.g. 9822001122 or ramesh@demo.com",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Enter your password",
    "signInButton": "Sign In to Account",
    "quickDemoLogins": "Quick Demo Logins:",
    "farmerLabel": "Farmer:",
    "buyerLabel": "Buyer:",
    "passLabel": "Pass:",
    "dontHaveAccount": "Don't have an account yet?",
    "registerHere": "Register here",
    "govtInitiative": "Official Government Mandi Linkage Initiative",
    "moduleActiveText": "MODULE 02 ACTIVE • DEDUCTION-ADJUSTED REALISATION ENGINE",
    "agmarknetFeed": "| AGMARKNET v4.0 Linked Feed",
    "netRealisationTitle": "Net Realisation",
    "algoVersion": "v2.4 Algorithmic",
    "netRealisationDesc": "Find the market that gives you the highest expected net return after true logistics & grading frictions.",
    "farmOriginLabel": "FARM ORIGIN / DISPATCH",
    "editLabel": "Edit 📍",
    "operationalRealityTitle": "Operational Reality Principle:",
    "operationalRealityDesc": "KrishiVaani market recommendation calculates true net take-home by deducting actual transport cost, APMC cesses, loading/unloading fees, and perishability transit loss — not just quoted headline mandi rates.",
    "toleranceLabel": "TOLERANCE: <1.2%",
    "marketAnalysisSummary": "📊 Market Analysis Complete • Evaluated 14 Regional APMC Mandis • Freight Model:",
    "freightModelVal": "₹16/km (2T LCV Shared Route)",
    "topMandiLabel": "Displaying Top 5 Net Optimal Mandis ⚡",
    "calculatingMsg": "Calculating Net Realisation...",
    "integratedWorkflowLabel": "INTEGRATED FARMER WORKFLOW",
    "nextDecisionsTitle": "Next Decisions for Your {quantity} Q {crop} Lot",
    "lotSpecsDesc": "Your lot specifications are saved and will transfer automatically without re-entering parameters.",
    "viewFpoOrders": "View Active FPO Orders",
    "sellWaitTitle": "04 Sell Now / Wait",
    "sellWaitDesc": "Evaluate storage cost vs. projected price upside against incoming weather hazards.",
    "evaluateHolding": "Evaluate Holding Timing",
    "buyerMatchingDesc": "Receive direct farm-gate bids with zero mandi cess and guaranteed escrow settlement.",
    "findVerifiedBuyers": "Find Verified Buyers",
    "farmerFirstEcosystem": "Farmer-First Ecosystem",
    "createAccountTitle": "Create your KrishiVaani Account",
    "joinSubtitle": "Join thousands of verified farmers & institutional buyers across Maharashtra",
    "selectRoleLabel": "Select your platform role",
    "alreadyRegistered": "Already registered with KrishiVaani?",
    "signInLink": "Sign in to your account",
    "sellWaitFarmerAdvisory": "FARMER ADVISORY",
    "sellWaitTimingGuide": "TIMING GUIDE",
    "sellWaitPageTitle": "Sell Now or Wait?",
    "sellWaitPageDescription": "Use current price, market trends, weather, crop condition and storage information to compare your options.",
    "sellWaitWeatherMandiSync": "WEATHER & MANDI SYNC",
    "sellWaitImdAdvisory": "IMD Pune Agro-Met Advisory Live",
    "sellWaitFeaturesSub1": "● Simple Selling-Time Decision Assistant • Real-Time Mandi Data Active",
    "sellWaitFeaturesSub2": "Weather synced with IMD Pune Agro-Met Advisory"
  },
  "mr": {
    "kisanCallCentre": "किसान कॉल सेंटर:",
    "farmerFirst": "शेतकरी प्रथम",
    "tagline": "शेतकऱ्यांसाठी बाजारपेठ जोडणी आणि पारदर्शक भाव शोध",
    "priceDiscovery": "०१ भाव शोध (Price Discovery)",
    "netRealisation": "०२ निव्वळ नफा (Net Realisation)",
    "fpoAggregation": "०३ एफपीओ एकत्रीकरण (FPO Aggregation)",
    "sellWait": "०४ विक्री करावी की थांबावे (Sell / Wait)",
    "buyerMatching": "०५ थेट खरेदीदार व लिलाव (Bidding)",
    "cropRescue": "पीक बचाव",
    "verifiedMandi": "e-NAM मानके प्रमाणित",
    "sihPrototype": "स्मार्ट इंडिया हॅकाथॉन २०२४–२६ प्रोटोटाईप",
    "helplineHours": "किसान हेल्पलाईन: १८००-१८०-१५५१ (सोम-शनि, ०६:०० - २०:०० IST)",
    "directBuyerConnection": "थेट खरेदीदार संपर्क",
    "zeroIntermediaryDeductions": "शून्य मध्यस्थ कपात",
    "buyerMatchingTitle": "०५ थेट खरेदीदार जुळणी",
    "buyerMatchingSubtitle": "तुमच्या शेतात किंवा गोदामात काय आहे ते सांगा. आम्ही तुम्हाला थेट सत्यापित संस्थात्मक खरेदीदार, अन्न प्रक्रिया करणारे आणि रिटेल चेनशी जोडतो.",
    "activeBuyers": "सक्रिय खरेदीदार",
    "defaultActiveBuyers": "१८ सक्रिय खरेदीदार",
    "readyIn": "मध्ये तयार आहे",
    "cluster": "क्लस्टर",
    "escrowGuaranteed": "🔒 100% हमी",
    "step1Listed": "१. उत्पादन सूचीबद्ध",
    "step2Matched": "२. जुळणारे खरेदीदार",
    "step3Terms": "३. योग्य अटी",
    "step4Offer": "४. सक्रिय ऑफर",
    "step5Deal": "५. डिजिटल डील",
    "step6Dispatch": "६. पाठवणे आणि DBT",
    "topLeads": "शीर्ष लीड्स",
    "gatePickups": "गेट पिकअप्स",
    "lockEscrow": "एस्क्रो लॉक करा",
    "bankPayout": "२४ तासांत बँक पेमेंट",
    "matchingVerifiedBuyers": "सत्यापित संस्थात्मक खरेदीदार जुळवत आहे...",
    "noMatchingBuyersFound": "यासाठी कोणतेही जुळणारे खरेदीदार सापडले नाहीत",
    "tryDifferentCrop": "वेगळे पीक वापरून पहा किंवा प्रमाण कमी करा.",
    "emergencyDispatchContingency": "आणीबाणी डिस्पॅच आकस्मिकता",
    "emergencyDispatchDesc": "खरेदीदाराने रद्द करणे, गेटवर नकार देणे किंवा वाहतुकीस विलंब यासारख्या समस्यांचा सामना करत आहात?",
    "openCropRescue": "क्रॉप रेस्क्यू उघडा (मॉड्यूल ०६) →",
    "enamCompliant": "🔒 ई-नाम मानक अनुरूप • ॲग्रीस्टॅक प्रोटोकॉल नोड #412",
    "fetchBuyersFailed": "जुळणारे खरेदीदार आणण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    "offerSent": "✅ ऑफर पाठवली",
    "andSavedBid": "आणि जतन केली (बोली #",
    "sendOfferFailed": "ऑफर पाठवण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    "counterOfferSent": "काउंटर-ऑफर",
    "sentTo": "ला पाठवली",
    "counterOfferFailed": "काउंटर-ऑफर अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    "dealConfirmed": "🎉 डील निश्चित",
    "transactionCreated": "तयार केले.",
    "acceptOfferFailed": "ऑफर स्वीकारण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    "offerDeclined": "ऑफर नाकारली.",
    "offerFrom": "कडून ऑफर",
    "declined": "नाकारली.",
    "declineConfirm1": "ची ऑफर नाकारायची?",
    "declineConfirm2": "हे पूर्ववत केले जाऊ शकत नाही.",
    "downloadingContract": "📄 ई-नाम डिजिटल करार PDF डाउनलोड करत आहे...",
    "gatePassGenerated": "🎟️ डिस्पॅच गेट पास तयार झाला. FPO हबमध्ये अहवाल द्या.",
    "emergencyModeActive": "आणीबाणी मोड सक्रिय",
    "clusterLabel": "समूह:",
    "apmcYardLabel": "एपीएमसी यार्ड",
    "cropRescueDesc": "तुमच्या नियोजित पीक पाठवणीमध्ये काहीतरी चूक झाली? घाबरू नका. कृषिवाणी तत्काळ पर्यायी खरेदीदार, कोल्ड बे होल्ड्स आणि जवळील खुल्या मंडई यार्डांची व्यवस्था करते.",
    "avgFallbackResolution": "सरासरी पर्यायी उपाय:",
    "fourteenMins": "१४ मिनिटे",
    "hideIncidentHistory": "घटना इतिहास लपवा",
    "myIncidents": "माझ्या घटना",
    "step1Identified": "१. समस्या ओळखली",
    "buyer_cancelled_title": "खरेदीदाराने रद्द केले",
    "transport_problem_title": "वाहतूक समस्या",
    "quality_dispute_title": "गुणवत्ता विवाद",
    "other_emergency_title": "इतर आणीबाणी",
    "step2RescueStrategy": "२. बचाव धोरण",
    "selectAltPath": "पर्यायी मार्ग निवडा",
    "step3InstantMatches": "३. झटपट सामने",
    "verifiedBuyers": "सत्यापित खरेदीदार",
    "step4TakeAction": "४. कृती करा",
    "dispatchOrSecure": "पाठवा किंवा सुरक्षित ठेवा",
    "registeredCasesTitle": "PostgreSQL मध्ये नोंदणीकृत बचाव प्रकरणे",
    "totalLoggedIncidents": "एकूण नोंदवलेल्या घटना",
    "failedLoadCrops": "सर्वरवरून पीक सूची लोड करण्यात अयशस्वी.",
    "failedFetchMandis": "जवळपासच्या बाजारातील भाव आणण्यात अयशस्वी.",
    "moduleActiveSync": "मॉड्यूल ०१ सक्रिय • ॲगमार्कनेट आणि ई-नाम सह समक्रमित",
    "updatedMinsAgo": "| १५ मिनिटांपूर्वी अद्यतनित (थेट फीड)",
    "priceDiscoveryTitle": "किंमत शोध",
    "priceDiscoverySubtitle": "तुमचे उत्पादन शेताबाहेर नेण्यापूर्वी स्थानिक कृषी उत्पन्न बाजार समित्यांचे चालू बाजारभाव तपासा.",
    "originLocationCaps": "मूळ ठिकाण",
    "changeLocationBtn": "बदला 📍",
    "selectYourCropTitle": "तुमचे पीक निवडा",
    "clickCommodityHint": "एपीएमसी यार्ड किमती अद्ययावत करण्यासाठी कोणत्याही वस्तूवर क्लिक करा",
    "loadingCropsMsg": "पिकांच्या वस्तू लोड होत आहेत...",
    "moreCropsBtn": "+४१ अधिक",
    "allIndiaIndexTxt": "अखिल भारतीय निर्देशांक",
    "nearbySpotPricesTitle": "जवळपासच्या एपीएमसी बाजाराचे स्पॉट भाव",
    "mandiGradeTxt": "मंडी ग्रेड: एफएक्यू संकरित",
    "fetchingVerifiedPricesWithin": "आत सत्यापित स्पॉट भाव आणत आहे",
    "kmSuffix": "किमी...",
    "noMandisFoundWithin": "आत कोणतीही एपीएमसी मंडी सापडली नाही",
    "km": "किमी",
    "expandSearchRadiusHint": "तुमची शोध त्रिज्या ५० किमी किंवा १०० किमी पर्यंत वाढवण्याचा प्रयत्न करा, किंवा खाली विशिष्ट बाजारपेठ शोधा.",
    "expandRadius100kmBtn": "त्रिज्या १०० किमी पर्यंत वाढवा",
    "module3Active": "मॉड्यूल ०३ सक्रिय • एफपीओ उत्पादन संकलन आणि करार पूर्तता",
    "fpoAggregationTitle": "०३ FPO एकत्रीकरण",
    "fpoAggregationDesc": "संस्थात्मक ऑर्डर्स पूर्ण करण्यासाठी तुमचे {quantity} क्विंटल शेजारील शेतकऱ्यांसोबत एकत्र करा.",
    "enamFpoGateway": "ई-नाम एफपीओ गेटवे v4.2",
    "baramatiKisanProducer": "बारामती किसान प्रोड्यूसर कं. (नोंदणी: FPO-MH-2024-882)",
    "step01BuyerRequirement": "पायरी ०१: खरेदीदाराची आवश्यकता",
    "step02FilterFarmers": "पायरी ०२: शेतकऱ्यांना फिल्टर करा",
    "step03AggregateQuantity": "पायरी ०३: प्रमाण एकत्रित करा",
    "step04GenerateFpoLot": "पायरी ०४: एफपीओ लॉट तयार करा",
    "step05ContractPayout": "पायरी ०५: करार पेआउट",
    "loadingVerifiedBuyerReqs": "सत्यापित खरेदीदार आवश्यकता लोड करत आहे...",
    "buyerPurchaseOfferAccepted": "🎉 खरेदीदाराची खरेदी ऑफर स्वीकारली! ई-नाम एस्क्रो करार #AGR-MH-2026-904 सक्रिय झाला.",
    "counterBidTransmitted": "काऊंटर-बिड (+₹१.००/किलो) संस्थात्मक खरेदी डेस्ककडे पाठवली.",
    "smartContractId": "स्मार्ट करार #SC-MH-2026-904",
    "zeroCommissionCompliant": "शून्य कमिशन मँडेट कंप्लायंट",
    "fastTrackSettlement": "फास्ट-ट्रॅक सेटलमेंट प्रोटोकॉल",
    "lastSyncInfo": "शेवटचा सिंक: आज, 11:42 AM IST • बारामती संकलन केंद्र",
    "loginTitle": "तुमची बाजारपेठ जाणून घ्या.",
    "loginSubtitle": "तुमची कमाई समजून घ्या.",
    "heroDesc": "पारदर्शक किंमत शोधाद्वारे भारतीय शेतकऱ्यांचे सक्षमीकरण.",
    "heroSubDesc": "संपूर्ण महाराष्ट्रामध्ये रिअल-टाइम APMC किंमत शोध, भाडे आणि कपातीनंतर पारदर्शक निव्वळ प्राप्तीसह, आणि सत्यापित खरेदीदारांशी थेट दुवा.",
    "farmersBuyersTitle": "शेतकरी आणि सत्यापित खरेदीदार",
    "farmersBuyersDesc": "सत्यापित संस्थात्मक खरेदीदारांसह पारदर्शक किंमत शोध.",
    "maharashtraMandisTitle": "महाराष्ट्र राज्य मंडई",
    "maharashtraMandisDesc": "थेट APMC बाजारभाव आणि बाजाराची माहिती.",
    "termsConditions": "अटी व शर्ती",
    "privacyPolicy": "गोपनीयता धोरण",
    "aboutUs": "आमच्याबद्दल",
    "allRightsReserved": "© 2025 कृषीवाणी. सर्व हक्क राखीव.",
    "securePortalAccess": "सुरक्षित पोर्टल प्रवेश",
    "welcomeTitle": "कृषीवाणी मध्ये आपले स्वागत आहे",
    "welcomeSubtitle": "किंमत शोध, खरेदीदार दुवे आणि मंडी अंतर्दृष्टी प्रवेश करण्यासाठी साइन इन करा",
    "errorEmptyId": "कृपया तुमचा मोबाईल नंबर किंवा ईमेल पत्ता प्रविष्ट करा",
    "errorEmptyPassword": "कृपया तुमचा पासवर्ड प्रविष्ट करा",
    "errorLoginFailed": "लॉगिन अयशस्वी. कृपया क्रेडेन्शियल्स तपासा.",
    "errorServer": "सर्व्हरशी कनेक्ट करण्यात अक्षम. कृपया पुन्हा प्रयत्न करा.",
    "mobileOrEmailLabel": "मोबाईल नंबर किंवा ईमेल",
    "mobileOrEmailPlaceholder": "उदा. 9822001122 किंवा ramesh@demo.com",
    "passwordLabel": "पासवर्ड",
    "passwordPlaceholder": "तुमचा पासवर्ड प्रविष्ट करा",
    "signInButton": "खात्यात साइन इन करा",
    "quickDemoLogins": "जलद डेमो लॉगिन:",
    "farmerLabel": "शेतकरी:",
    "buyerLabel": "खरेदीदार:",
    "passLabel": "पासवर्ड:",
    "dontHaveAccount": "अजून खाते नाही?",
    "registerHere": "येथे नोंदणी करा",
    "govtInitiative": "अधिकृत सरकारी मंडी लिंकेज उपक्रम",
    "moduleActiveText": "मॉड्यूल ०२ सक्रिय • कपात-समायोजित प्राप्ती इंजिन",
    "agmarknetFeed": "| AGMARKNET v4.0 लिंक केलेला फीड",
    "netRealisationTitle": "निव्वळ प्राप्ती",
    "algoVersion": "v2.4 अल्गोरिदमिक",
    "netRealisationDesc": "खरे लॉजिस्टिक आणि ग्रेडिंग खर्च वजा केल्यानंतर सर्वाधिक अपेक्षित निव्वळ परतावा देणारी बाजारपेठ शोधा.",
    "farmOriginLabel": "शेत मूळ / पाठवणे",
    "editLabel": "संपादित करा 📍",
    "operationalRealityTitle": "ऑपरेशनल रिअॅलिटी तत्त्व:",
    "operationalRealityDesc": "कृषीवाणी बाजाराची शिफारस फक्त कोट केलेले मथळा बाजार दर नाही तर वास्तविक वाहतूक खर्च, APMC उपकर, लोडिंग/अनलोडिंग फी आणि नाशवंत वाहतूक नुकसान वजा करून खरी निव्वळ रक्कम मोजते.",
    "toleranceLabel": "सहनशीलता: <१.२%",
    "marketAnalysisSummary": "📊 बाजार विश्लेषण पूर्ण • १४ प्रादेशिक कृषी उत्पन्न बाजार समित्यांचे मूल्यांकन केले • मालवाहतूक मॉडेल:",
    "freightModelVal": "₹१६/किमी (२T LCV सामायिक मार्ग)",
    "topMandiLabel": "शीर्ष ५ निव्वळ इष्टतम बाजार प्रदर्शित करत आहे ⚡",
    "calculatingMsg": "निव्वळ प्राप्तीची गणना करत आहे...",
    "integratedWorkflowLabel": "एकात्मिक शेतकरी कार्यप्रवाह",
    "nextDecisionsTitle": "तुमच्या {quantity} क्विंटल {crop} लॉटसाठी पुढील निर्णय",
    "lotSpecsDesc": "तुमची लॉटची वैशिष्ट्ये जतन केली आहेत आणि पॅरामीटर्स पुन्हा न टाकता आपोआप हस्तांतरित होतील.",
    "viewFpoOrders": "सक्रिय FPO ऑर्डर्स पहा",
    "sellWaitTitle": "०४ आता विका / थांबा",
    "sellWaitDesc": "आगामी हवामानाच्या धोक्यांविरुद्ध साठवणूक खर्च वि. अंदाजित किमतीच्या वाढीचे मूल्यांकन करा.",
    "evaluateHolding": "होल्डिंगच्या वेळेचे मूल्यांकन करा",
    "buyerMatchingDesc": "शून्य बाजार उपकर आणि हमी एस्क्रो सेटलमेंटसह थेट शेतातील बोली मिळवा.",
    "findVerifiedBuyers": "सत्यापित खरेदीदार शोधा",
    "farmerFirstEcosystem": "शेतकरी-प्रथम परिसंस्था",
    "createAccountTitle": "तुमचे कृषीवाणी खाते तयार करा",
    "joinSubtitle": "महाराष्ट्रातील हजारो सत्यापित शेतकरी आणि संस्थात्मक खरेदीदारांमध्ये सामील व्हा",
    "selectRoleLabel": "तुमची प्लॅटफॉर्म भूमिका निवडा",
    "alreadyRegistered": "कृषीवाणीवर आधीपासून नोंदणीकृत आहात?",
    "signInLink": "तुमच्या खात्यात साइन इन करा",
    "sellWaitFarmerAdvisory": "शेतकरी सल्ला",
    "sellWaitTimingGuide": "वेळ मार्गदर्शक",
    "sellWaitPageTitle": "आता विकावे की वाट पाहावी?",
    "sellWaitPageDescription": "तुमचे पर्याय तपासण्यासाठी सध्याची किंमत, बाजार कल, हवामान, पिकाची स्थिती आणि साठवणूक माहिती वापरा.",
    "sellWaitWeatherMandiSync": "हवामान आणि बाजार सिंक",
    "sellWaitImdAdvisory": "IMD पुणे कृषी-हवामान सल्ला थेट",
    "sellWaitFeaturesSub1": "● सोपे विक्री-वेळ निर्णय सहाय्यक • रिअल-टाइम बाजार डेटा सक्रिय",
    "sellWaitFeaturesSub2": "IMD पुणे कृषी-हवामान सल्ल्यानुसार हवामान सिंक केले"
  },
  "hi": {
    "kisanCallCentre": "किसान कॉल सेंटर:",
    "farmerFirst": "किसान प्रथम",
    "tagline": "किसानों के लिए बाजार संपर्क और सही मूल्य निर्धारण",
    "priceDiscovery": "०१ मूल्य खोज (Price Discovery)",
    "netRealisation": "०२ शुद्ध प्राप्ति (Net Realisation)",
    "fpoAggregation": "०३ एफपीओ एकत्रीकरण (FPO Aggregation)",
    "sellWait": "०४ अभी बेचें या प्रतीक्षा करें (Sell / Wait)",
    "buyerMatching": "०५ खरीदार मिलान और बोली (Bidding)",
    "cropRescue": "फसल बचाव",
    "verifiedMandi": "e-NAM मानक प्रमाणित",
    "sihPrototype": "स्मार्ट इंडिया हैकाथॉन २०२४–२६ प्रोटोटाइप",
    "helplineHours": "किसान हेल्पलाइन: १८००-१८०-१५५१ (सोम-शनि, ०६:०० - २०:०० IST)",
    "directBuyerConnection": "सीधा खरीदार संपर्क",
    "zeroIntermediaryDeductions": "शून्य मध्यस्थ कटौती",
    "buyerMatchingTitle": "05 सीधा खरीदार मिलान",
    "buyerMatchingSubtitle": "हमें बताएं कि आपके खेत या गोदाम में क्या है। हम आपको सीधे सत्यापित संस्थागत खरीदारों, खाद्य प्रसंस्करणकर्ताओं और रिटेल चेन से जोड़ते हैं।",
    "activeBuyers": "सक्रिय खरीदार",
    "defaultActiveBuyers": "18 सक्रिय खरीदार",
    "readyIn": "में तैयार",
    "cluster": "क्लस्टर",
    "escrowGuaranteed": "🔒 100% एस्क्रो गारंटी",
    "step1Listed": "1. उपज सूचीबद्ध",
    "step2Matched": "2. मेल खाने वाले खरीदार",
    "step3Terms": "3. उपयुक्त शर्तें",
    "step4Offer": "4. सक्रिय ऑफर",
    "step5Deal": "5. डिजिटल डील",
    "step6Dispatch": "6. प्रेषण और DBT",
    "topLeads": "शीर्ष लीड्स",
    "gatePickups": "गेट पिकअप",
    "lockEscrow": "एस्क्रो लॉक करें",
    "bankPayout": "24 घंटे में बैंक भुगतान",
    "matchingVerifiedBuyers": "सत्यापित संस्थागत खरीदारों का मिलान हो रहा है...",
    "noMatchingBuyersFound": "के लिए कोई मेल खाने वाले खरीदार नहीं मिले",
    "tryDifferentCrop": "एक अलग फसल की कोशिश करें या मात्रा कम करें।",
    "emergencyDispatchContingency": "आपातकालीन प्रेषण आकस्मिकता",
    "emergencyDispatchDesc": "खरीदार द्वारा रद्दीकरण, गेट पर अस्वीकृति, या परिवहन में देरी का सामना कर रहे हैं?",
    "openCropRescue": "फसल बचाव खोलें (मॉड्यूल 06) →",
    "enamCompliant": "🔒 ई-नाम मानक अनुपालन • एग्रीस्टैक प्रोटोकॉल नोड #412",
    "fetchBuyersFailed": "मिलान करने वाले खरीदारों को लाने में विफल। कृपया पुन: प्रयास करें।",
    "offerSent": "✅ ऑफर भेजा गया",
    "andSavedBid": "और सहेजा गया (बोली #",
    "sendOfferFailed": "ऑफर भेजने में विफल। कृपया पुन: प्रयास करें।",
    "counterOfferSent": "काउंटर-ऑफर",
    "sentTo": "को भेजा गया",
    "counterOfferFailed": "काउंटर-ऑफर विफल रहा। कृपया पुन: प्रयास करें।",
    "dealConfirmed": "🎉 डील पक्की",
    "transactionCreated": "बनाया गया।",
    "acceptOfferFailed": "ऑफर स्वीकार करने में विफल। कृपया पुन: प्रयास करें।",
    "offerDeclined": "ऑफर अस्वीकार कर दिया गया।",
    "offerFrom": "से ऑफर",
    "declined": "अस्वीकार कर दिया गया।",
    "declineConfirm1": "का ऑफर अस्वीकार करें?",
    "declineConfirm2": "इसे पूर्ववत नहीं किया जा सकता है।",
    "downloadingContract": "📄 ई-नाम डिजिटल अनुबंध पीडीएफ डाउनलोड हो रहा है...",
    "gatePassGenerated": "🎟️ प्रेषण गेट पास जनरेट किया गया। एफपीओ हब में रिपोर्ट करें।",
    "emergencyModeActive": "आपातकालीन मोड सक्रिय",
    "clusterLabel": "क्लस्टर:",
    "apmcYardLabel": "एपीएमसी यार्ड",
    "cropRescueDesc": "क्या आपके निर्धारित फसल प्रेषण में कुछ गलत हो गया? घबराएं नहीं। कृषिवानी तुरंत वैकल्पिक खरीदारों, कोल्ड बे होल्ड्स और पास के खुले मंडी यार्डों की व्यवस्था करता है।",
    "avgFallbackResolution": "औसत वैकल्पिक समाधान:",
    "fourteenMins": "14 मिनट",
    "hideIncidentHistory": "घटना इतिहास छिपाएं",
    "myIncidents": "मेरी घटनाएँ",
    "step1Identified": "1. समस्या की पहचान",
    "buyer_cancelled_title": "खरीदार ने रद्द किया",
    "transport_problem_title": "परिवहन समस्या",
    "quality_dispute_title": "गुणवत्ता विवाद",
    "other_emergency_title": "अन्य आपात स्थिति",
    "step2RescueStrategy": "2. बचाव रणनीति",
    "selectAltPath": "वैकल्पिक मार्ग चुनें",
    "step3InstantMatches": "3. त्वरित मिलान",
    "verifiedBuyers": "सत्यापित खरीदार",
    "step4TakeAction": "4. कार्रवाई करें",
    "dispatchOrSecure": "भेजें या सुरक्षित रखें",
    "registeredCasesTitle": "PostgreSQL में पंजीकृत बचाव मामले",
    "totalLoggedIncidents": "कुल दर्ज घटनाएँ",
    "failedLoadCrops": "सर्वर से फसल सूची लोड करने में विफल।",
    "failedFetchMandis": "आसपास की मंडियों की कीमतें लाने में विफल।",
    "moduleActiveSync": "मॉड्यूल 01 सक्रिय • एगमार्कनेट और ई-नाम के साथ सिंक किया गया",
    "updatedMinsAgo": "| 15 मिनट पहले अपडेट किया गया (लाइव फ़ीड)",
    "priceDiscoveryTitle": "मूल्य खोज",
    "priceDiscoverySubtitle": "अपनी उपज को खेत से बाहर ले जाने से पहले स्थानीय एपीएमसी मंडियों में वर्तमान हाजिर कीमतों की जाँच करें।",
    "originLocationCaps": "मूल स्थान",
    "changeLocationBtn": "बदलें 📍",
    "selectYourCropTitle": "अपनी फसल चुनें",
    "clickCommodityHint": "एपीएमसी यार्ड की कीमतों को अपडेट करने के लिए किसी भी वस्तु पर क्लिक करें",
    "loadingCropsMsg": "फसल वस्तुओं को लोड किया जा रहा है...",
    "moreCropsBtn": "+41 अधिक",
    "allIndiaIndexTxt": "अखिल भारतीय सूचकांक",
    "nearbySpotPricesTitle": "आसपास की एपीएमसी मंडियों की हाजिर कीमतें",
    "mandiGradeTxt": "मंडी ग्रेड: एफएक्यू हाइब्रिड",
    "fetchingVerifiedPricesWithin": "के भीतर सत्यापित हाजिर कीमतें प्राप्त की जा रही हैं",
    "kmSuffix": "किमी...",
    "noMandisFoundWithin": "के भीतर कोई एपीएमसी मंडी नहीं मिली",
    "km": "किमी",
    "expandSearchRadiusHint": "अपने खोज दायरे को 50 किमी या 100 किमी तक बढ़ाने का प्रयास करें, या नीचे एक विशिष्ट बाजार खोजें।",
    "expandRadius100kmBtn": "दायरा 100 किमी तक बढ़ाएं",
    "module3Active": "मॉड्यूल 03 सक्रिय • एफपीओ उत्पाद एकत्रीकरण और अनुबंध पूर्ति",
    "fpoAggregationTitle": "03 FPO एकत्रीकरण",
    "fpoAggregationDesc": "संस्थागत आदेशों को पूरा करने के लिए अपने {quantity} क्विंटल को पड़ोसी किसानों के साथ मिलाएं।",
    "enamFpoGateway": "ई-नाम एफपीओ गेटवे v4.2",
    "baramatiKisanProducer": "बारामती किसान प्रोड्यूसर कं. (पंजीकरण: FPO-MH-2024-882)",
    "step01BuyerRequirement": "चरण 01: खरीदार की आवश्यकता",
    "step02FilterFarmers": "चरण 02: किसानों को फ़िल्टर करें",
    "step03AggregateQuantity": "चरण 03: मात्रा एकत्रित करें",
    "step04GenerateFpoLot": "चरण 04: एफपीओ लॉट उत्पन्न करें",
    "step05ContractPayout": "चरण 05: अनुबंध पेआउट",
    "loadingVerifiedBuyerReqs": "सत्यापित खरीदार आवश्यकताओं को लोड किया जा रहा है...",
    "buyerPurchaseOfferAccepted": "🎉 खरीदार खरीद प्रस्ताव स्वीकार कर लिया गया! ई-नाम एस्क्रो अनुबंध #AGR-MH-2026-904 सक्रिय।",
    "counterBidTransmitted": "काउंटर-बोली (+₹1.00/किग्रा) संस्थागत खरीद डेस्क को प्रेषित की गई।",
    "smartContractId": "स्मार्ट अनुबंध #SC-MH-2026-904",
    "zeroCommissionCompliant": "शून्य कमीशन मैंडेट कंप्लायंट",
    "fastTrackSettlement": "फास्ट-ट्रैक सेटलमेंट प्रोटोकॉल",
    "lastSyncInfo": "अंतिम सिंक: आज, 11:42 AM IST • बारामती एकत्रीकरण केंद्र",
    "loginTitle": "अपना बाज़ार जानें।",
    "loginSubtitle": "अपनी कमाई समझें।",
    "heroDesc": "पारदर्शी मूल्य खोज के माध्यम से भारतीय किसानों को सशक्त बनाना।",
    "heroSubDesc": "माल ढुलाई और कटौती के बाद पारदर्शी शुद्ध प्राप्ति और सत्यापित खरीदारों के साथ सीधे संबंध के साथ पूरे महाराष्ट्र में वास्तविक समय एपीएमसी मूल्य खोज।",
    "farmersBuyersTitle": "किसान और सत्यापित खरीदार",
    "farmersBuyersDesc": "सत्यापित संस्थागत खरीदारों के साथ पारदर्शी मूल्य खोज।",
    "maharashtraMandisTitle": "महाराष्ट्र राज्य मंडियां",
    "maharashtraMandisDesc": "लाइव एपीएमसी मंडी दर और बाजार की जानकारी।",
    "termsConditions": "नियम और शर्तें",
    "privacyPolicy": "गोपनीयता नीति",
    "aboutUs": "हमारे बारे में",
    "allRightsReserved": "© 2025 कृषिवानी। सर्वाधिकार सुरक्षित।",
    "securePortalAccess": "सुरक्षित पोर्टल पहुंच",
    "welcomeTitle": "कृषिवानी में आपका स्वागत है",
    "welcomeSubtitle": "मूल्य खोज, खरीदार लिंक और मंडी अंतर्दृष्टि तक पहुंचने के लिए साइन इन करें",
    "errorEmptyId": "कृपया अपना मोबाइल नंबर या ईमेल पता दर्ज करें",
    "errorEmptyPassword": "कृपया अपना पासवर्ड दर्ज करें",
    "errorLoginFailed": "लॉगिन विफल। कृपया क्रेडेंशियल जांचें।",
    "errorServer": "सर्वर से कनेक्ट करने में असमर्थ। कृपया पुनः प्रयास करें।",
    "mobileOrEmailLabel": "मोबाइल नंबर या ईमेल",
    "mobileOrEmailPlaceholder": "उदा. 9822001122 या ramesh@demo.com",
    "passwordLabel": "पासवर्ड",
    "passwordPlaceholder": "अपना पासवर्ड दर्ज करें",
    "signInButton": "खाते में साइन इन करें",
    "quickDemoLogins": "त्वरित डेमो लॉगिन:",
    "farmerLabel": "किसान:",
    "buyerLabel": "खरीदार:",
    "passLabel": "पास:",
    "dontHaveAccount": "क्या आपके पास अभी तक कोई खाता नहीं है?",
    "registerHere": "यहाँ रजिस्टर करें",
    "govtInitiative": "आधिकारिक सरकारी मंडी लिंकेज पहल",
    "moduleActiveText": "मॉड्यूल 02 सक्रिय • कटौती-समायोजित प्राप्ति इंजन",
    "agmarknetFeed": "| AGMARKNET v4.0 लिंक्ड फीड",
    "netRealisationTitle": "शुद्ध प्राप्ति",
    "algoVersion": "v2.4 एल्गोरिथम",
    "netRealisationDesc": "वह बाज़ार खोजें जो आपको वास्तविक लॉजिस्टिक और ग्रेडिंग खर्चों में कटौती के बाद सबसे अधिक अपेक्षित शुद्ध रिटर्न देता है।",
    "farmOriginLabel": "खेत का मूल / प्रेषण",
    "editLabel": "संपादित करें 📍",
    "operationalRealityTitle": "परिचालन वास्तविकता सिद्धांत:",
    "operationalRealityDesc": "कृषिवानी बाजार अनुशंसा केवल उद्धृत हेडलाइन मंडी दरों को नहीं बल्कि वास्तविक परिवहन लागत, एपीएमसी उपकर, लोडिंग/अनलोडिंग शुल्क और पारगमन नुकसान में कटौती करके वास्तविक शुद्ध टेक-होम की गणना करती है।",
    "toleranceLabel": "सहिष्णुता: <1.2%",
    "marketAnalysisSummary": "📊 बाजार विश्लेषण पूर्ण • 14 क्षेत्रीय एपीएमसी मंडियों का मूल्यांकन किया गया • माल ढुलाई मॉडल:",
    "freightModelVal": "₹16/किमी (2T LCV साझा मार्ग)",
    "topMandiLabel": "शीर्ष 5 शुद्ध इष्टतम मंडियों का प्रदर्शन ⚡",
    "calculatingMsg": "शुद्ध प्राप्ति की गणना की जा रही है...",
    "integratedWorkflowLabel": "एकीकृत किसान वर्कफ़्लो",
    "nextDecisionsTitle": "आपके {quantity} क्विंटल {crop} लॉट के लिए अगले निर्णय",
    "lotSpecsDesc": "आपके लॉट के विनिर्देश सहेजे गए हैं और पैरामीटर फिर से दर्ज किए बिना स्वचालित रूप से स्थानांतरित हो जाएंगे।",
    "viewFpoOrders": "सक्रिय FPO आदेश देखें",
    "sellWaitTitle": "04 अभी बेचें / प्रतीक्षा करें",
    "sellWaitDesc": "आने वाले मौसम के खतरों के खिलाफ भंडारण लागत बनाम अनुमानित मूल्य वृद्धि का मूल्यांकन करें।",
    "evaluateHolding": "होल्डिंग समय का मूल्यांकन करें",
    "buyerMatchingDesc": "शून्य मंडी उपकर और गारंटीकृत एस्क्रो निपटान के साथ सीधे खेत-गेट की बोलियां प्राप्त करें।",
    "findVerifiedBuyers": "सत्यापित खरीदार खोजें",
    "farmerFirstEcosystem": "किसान-प्रथम पारिस्थितिकी तंत्र",
    "createAccountTitle": "अपना कृषीवाणी खाता बनाएं",
    "joinSubtitle": "महाराष्ट्र भर के हजारों सत्यापित किसानों और संस्थागत खरीदारों से जुड़ें",
    "selectRoleLabel": "अपनी प्लेटफॉर्म भूमिका चुनें",
    "alreadyRegistered": "कृषीवाणी पर पहले से पंजीकृत हैं?",
    "signInLink": "अपने खाते में साइन इन करें",
    "sellWaitFarmerAdvisory": "किसान सलाह",
    "sellWaitTimingGuide": "समय मार्गदर्शिका",
    "sellWaitPageTitle": "अभी बेचें या प्रतीक्षा करें?",
    "sellWaitPageDescription": "अपने विकल्पों की तुलना करने के लिए वर्तमान मूल्य, बाजार के रुझान, मौसम, फसल की स्थिति और भंडारण जानकारी का उपयोग करें।",
    "sellWaitWeatherMandiSync": "मौसम और मंडी सिंक",
    "sellWaitImdAdvisory": "IMD पुणे कृषि-मौसम सलाह लाइव",
    "sellWaitFeaturesSub1": "● सरल बिक्री-समय निर्णय सहायक • रीयल-टाइम मंडी डेटा सक्रिय",
    "sellWaitFeaturesSub2": "IMD पुणे कृषि-मौसम सलाह के साथ मौसम सिंक किया गया"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('krishi_lang') as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('krishi_lang', lang);
  };

  const t = (key: string, defaultText = ''): string => {
    return translations[language]?.[key] || translations.en[key] || defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
